theme = {
    "accent": "#ffc97b",
    "accent_negative": "#ff2c6d",
    "accent_positive": "#33ffe6",
    "background_content": "#1a1a82",
    "background_page": "#303aa5",
    "border": "#7892ff",
    "breakpoint_font": "1200px",
    "breakpoint_stack_blocks": "700px",
    "card_border": {
        "width": "0px",
        "style": "solid",
        "color": "#7892ff",
        "radius": "0px",
    },
    "card_background_color": "#303aa5",
    "card_box_shadow": "none",
    "card_margin": "15px",
    "card_padding": "5px",
    "card_outline": {"width": "1px", "style": "solid", "color": "#7892ff"},
    "card_header_border": {
        "width": "0px",
        "style": "solid",
        "color": "#7892ff",
        "radius": "0px",
    },
    "card_header_background_color": "#303aa5",
    "card_header_box_shadow": "0px 0px 0px rgba(0,0,0,0)",
    "card_header_margin": "0px",
    "card_header_padding": "10px",
    "colorway": [
        "#ffc97b",
        "#8dd3c7",
        "#ffffb3",
        "#bebada",
        "#fb8072",
        "#80b1d3",
        "#b3de69",
        "#fccde5",
        "#d9d9d9",
        "#bc80bd",
        "#ccebc5",
        "#ffed6f",
    ],
    "colorscale": [
        "#ffc97b",
        "#eab66c",
        "#d5a45e",
        "#c19150",
        "#ad8042",
        "#9a6e35",
        "#865d28",
        "#744d1b",
        "#613d0e",
        "#4f2e00",
    ],
    "font_family": "Montserrat",
    "font_size": "17px",
    "font_size_smaller_screen": "15px",
    "font_family_header": "Open Sans",
    "font_size_header": "24px",
    "font_family_headings": "Open Sans",
    "font_headings_size": None,
    "header_border": {
        "width": "0px",
        "style": "solid",
        "color": "#7892ff",
        "radius": "0px",
    },
    "header_background_color": "#303aa5",
    "header_box_shadow": None,
    "header_margin": "0px 0px 15px 0px",
    "header_padding": "0px",
    "text": "#d7e9ff",
    "report_font_family": "Computer Modern",
    "report_font_size": "12px",
    "report_background_page": "white",
    "report_background_content": "#FAFBFC",
    "report_text": "black",
}
